- name: Start hackimpott website
  docker_container:
    name: hackimpott-site
    image: hackimpott/site
    state: started
    pull: true
    restart_policy: always
    networks:
      - name: web
    labels: {
      traefik.basic.frontend.rule: "Host:hackimpott.de,www.hackimpott.de",
      traefik.frontend.headers.STSSeconds: "315360000",
      traefik.frontend.headers.STSIncludeSubdomains: "true",
      traefik.frontend.headers.STSPreload: "true",
      traefik.enable: "true"
    }
