version: '3'
services:
   traefik:
    #name: reverseproxy
    image: traefik:alpine
    #pull: true
    restart: always
    networks:
      - name: web
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "{{ docker_data_folder }}/traefik/traefik.toml:/etc/traefik/traefik.toml"
      - "{{ docker_data_folder }}/traefik/acme.json:/etc/traefik/acme.json"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels: {
      traefik.frontend.rule: "Host:traefik.dohms.chaospott.de",
      traefik.enable: "true",
      traefik.port: "8080",
      traefik.docker.network: "web"

networks:
  web:
    external: true
